### ISSUE TITLE
No visual display if a "hidden" monitor goes out of range

### ISSUE THREAD

**Issue by bs610** [MechanicalVentilatorMilano/gui#220]
If a monitor is not shown on the main screen, there is no visual display if it goes out of range. The GUI will tell the ESP32 that there is a problem, and the ESP will activate the LED/buzzer as appropriate, but the GUI shows nothing. The `ESP32Alarm` class specifically ignores code 29 so it will never appear in the top menu. The user will have to navigate to "Menu > Settings > Alarm settings" to understand which quantity is out of range. This seems very unintuitive.

One option is to show such "hidden" problems in the top alarm bar, customise the error string to indicate which values are out of range, and customise the Snooze action to act as if the monitor button had been pressed. There may be cleaner/better solutions.

**Comment by carmelopellegrino** [comment]
Actually, it was requested to remove all hidden monitors and alarms. This is why by default the only non-displayed monitor has no alarm. If doctors know how remove alarms, they should also know that have to check in the "Menu > Settings > Alarm settings" pane. Though it is not a perfect. A possible solution would be to prevent the doctor from hiding the not-alarmed monitors by disabling the "Move off" button on those monitors or by adding a button for hidden ones that if clicked automatically goes in the `Alarm settings` pane. Code 29 is ignored because the correct way to snooze it is to acknowledge all GUI alarms one by one.
